{"name": "test_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <case.test_login.TestLogin object at 0x000002B9609A2B20>\n\n    def test_002(self):\n>       assert 0\nE       assert 0\n\ncase\\test_login.py:5: AssertionError"}, "start": 1600156849384, "stop": 1600156849384, "uuid": "9cdc1d72-aa63-403a-a16e-719a6d7ec307", "historyId": "665162fb6b7c461bbad8c0012b8adf40", "testCaseId": "244fcb4882b3159049f2e036be67a18d", "fullName": "case.test_login.TestLogin#test_002", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UBGS01I"}, {"name": "thread", "value": "14636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_login"}]}